"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AUTHENTICATION_SELF_DOMAIN = exports.AUTHENTICATION_SECRET_KEY = exports.AUTHENTICATION_MONGO_DB = void 0;
exports.AUTHENTICATION_MONGO_DB = process.env.AUTHENTICATION_MONGO_DB;
exports.AUTHENTICATION_SECRET_KEY = process.env.AUTHENTICATION_SECRET_KEY;
exports.AUTHENTICATION_SELF_DOMAIN = process.env.AUTHENTICATION_SELF_DOMAIN;
