/**
 * @author WMXPY
 * @namespace Error
 * @description Code
 */

export enum ERROR_CODE {

    INVALID_DOMAIN_1 = 400180,

    APPLICATION_NOT_INITIALIZED = 500100,
    ENVIRONMENT_VARIABLE_REQUIRED_BUT_NOT_FOUND_1 = 500101,

    APPLICATION_INITIALIZED_WITH_INFO_MISSING_1 = 500205,
}
